blank_issues_enabled: false
contact_links:
  - name: Organization Support
    url: https://github.com/orgs/amplify-lk/discussions
    about: Use this for general questions or discussions.

issue_templates:
  - name: Bug Report
    description: Report a problem with the system.
    labels: ["bug"]
    body: bug_report.md

  - name: Feature Request
    description: Suggest a new feature or enhancement.
    labels: ["enhancement"]
    body: feature_request.md

